# Basic Tensor operations


https://github.com/sasidhar-programmer/Tensorflow_Advance_Techniques/blob/main/2-custom_and_distributed_training/week-1/C2_W1_Lab_1_basic-tensors.ipynb

In [7]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.5.0


In [8]:
# lets create a single dim np array
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
# now we want to tturn that array into a tensor
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [10]:
# let's square the elements of the 1d tensor
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [12]:
## One cool thing about tensors is that they can be reshaped
# here we change the shape of the tensor from 1x5 ternsor to a 5x5 tensor (matrix)

x = tf.reshape(x, (5,5), name="reshaped-tensor")
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [17]:
# note that if the shape passed isnt possibel with the tensor we will get an error
#if we reshape into a too small a shape
try:
	x = tf.reshape(x, (2,5))
except Exception as e:
	print("Exception: ", e)

Exception:  Input to reshape is a tensor with 25 values, but the requested shape has 10 [Op:Reshape]


In [18]:
# if we give it a shape too big for the data
try:
	x = tf.reshape(x, (10,10))
except Exception as e:
	print("Exception: ", e)

Exception:  Input to reshape is a tensor with 25 values, but the requested shape has 100 [Op:Reshape]


In [21]:
# now we give a possible shape
x = tf.reshape(x, (25, 1))
x

<tf.Tensor: shape=(25, 1), dtype=int64, numpy=
array([[  0],
       [  1],
       [  4],
       [  9],
       [ 16],
       [ 25],
       [ 36],
       [ 49],
       [ 64],
       [ 81],
       [100],
       [121],
       [144],
       [169],
       [196],
       [225],
       [256],
       [289],
       [324],
       [361],
       [400],
       [441],
       [484],
       [529],
       [576]])>

In [24]:
# we can also do the transponse operation
x = tf.transpose(x)
x

<tf.Tensor: shape=(1, 25), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
        169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576]])>

In [25]:
# we can change the datatype of the tensor
x= tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(1, 25), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.,
        121., 144., 169., 196., 225., 256., 289., 324., 361., 400., 441.,
        484., 529., 576.]], dtype=float32)>

In [26]:
# we can multiply a tensor by a scaler, ie a constant num
# this is called `broadcasting`
y = tf.constant(2, dtype=tf.float32)
print("the scaler is ", y)

result = tf.multiply(x, y)
result

the scaler is  tf.Tensor(2.0, shape=(), dtype=float32)


<tf.Tensor: shape=(1, 25), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.,   50.,   72.,   98.,  128.,
         162.,  200.,  242.,  288.,  338.,  392.,  450.,  512.,  578.,
         648.,  722.,  800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [28]:
# We can add tensors even if they have mismatched number of rows

x = tf.reshape(x, (5,5))# change shape to make it same col num as y
y = tf.constant([1,2,3,4,5], dtype=tf.float32)

print("y is", y)
print("x is: ", x)

result = x + y # element wise addition
print('x+y = ',  result)

y is tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
x is:  tf.Tensor(
[[  0.   1.   4.   9.  16.]
 [ 25.  36.  49.  64.  81.]
 [100. 121. 144. 169. 196.]
 [225. 256. 289. 324. 361.]
 [400. 441. 484. 529. 576.]], shape=(5, 5), dtype=float32)
x+y =  tf.Tensor(
[[  1.   3.   7.  13.  21.]
 [ 26.  38.  52.  68.  86.]
 [101. 123. 147. 173. 201.]
 [226. 258. 292. 328. 366.]
 [401. 443. 487. 533. 581.]], shape=(5, 5), dtype=float32)


In [30]:
# note a difference between setting up a tf.constant and a tf.Variable

# here we can pass a 1D array and choose an output shape, and it will work, tf.Variable will not however
tf.constant([1,2,3,4], shape=(2,2))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [31]:
# unlike tf.constant, tf.Variable can't take a shape. This is because the shape is dereived from the shape of the passed array
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).


In [34]:
# both constants and variables can be reshaped just fine after they are initalized


## we can reshape tf.Variables just fine
x = tf.Variable([1,2,3,4])
print(x)
x = tf.reshape(x,(2,2))
x


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)> tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [35]:
# and we can reshape constants just fine too!
x = tf.constant([1,2,3,4])
x = tf.reshape(x,(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>